spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: monew
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info
